# Generated by Django 2.2.6 on 2019-10-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
